cosmetics+checksum verification of downloaded file

diff --git a/.copr/Makefile b/.copr/Makefile
--- a/.copr/Makefile
+++ b/.copr/Makefile
@@ -6,46 +6,56 @@ curl:
 
 download: rpmdev-spectool curl
 	rpmdev-spectool $(spec) | awk '$$1 ~ /^Source/ && $$2 ~ /^http/ { print $$2 }' | while read url; do \
-		echo "INFO  : Download source if missing or checksum not equal: $$url"; \
 		file=$$(basename $$url); \
 		package=$$(echo $$file | sed 's/-[0-9].*//g'); \
+		echo "INFO  : download source  $$file"; \
 		urlIndex="https://pypi.org/simple/$$package/"; \
-		echo "INFO  : Download index for $$package: $$urlIndex"; \
+		echo "INFO  : download index   $$package: $$urlIndex"; \
 		indexEntry=$$(curl -L -s $$urlIndex | grep ">$$file<"); \
 		checksumEntry=$$(echo "$$indexEntry" | sed 's/.*sha256=\([0-9a-f]*\)".*/\1/g'); \
 		urlEntry=$$(echo "$$indexEntry" | sed 's/.*href="\(.*\)#.*/\1/g'); \
 		if [ -n "$$indexEntry" -a -n "$$checksumEntry" -a -n "$$urlEntry" ]; then \
-			echo "INFO  : Download index for $$package: $$urlIndex (SUCCESSFUL)"; \
+			echo "INFO  : download index   $$package: $$urlIndex (SUCCESSFUL)"; \
 		else \
-			echo "ERROR : Download index for $$package: $$urlIndex (NOT-SUCCESSFUL)"; \
-			echo "ERROR : Download index for $$package: indexEntry=$$indexEntry"; \
-			echo "ERROR : Download index for $$package: checksumEntry=$$checksumEntry"; \
-			echo "ERROR : Download index for $$package: urlEntry=$$urlEntry"; \
+			echo "ERROR : download index   $$package: $$urlIndex (NOT-SUCCESSFUL)"; \
+			echo "ERROR : download index   $$package: indexEntry=$$indexEntry"; \
+			echo "ERROR : download index   $$package: checksumEntry=$$checksumEntry"; \
+			echo "ERROR : download index   $$package: urlEntry=$$urlEntry"; \
 			exit 1; \
 		fi; \
 		if [ -e $$file ]; then \
-			echo "INFO  : index entry for $$file has checksum: $$checksumEntry"; \
+			echo "INFO  : index entry for  $$file has checksum: $$checksumEntry"; \
 			checksumExisting=$$(sha256sum $$file | awk '{ print $$1 }'); \
-			echo "INFO  : local $$file has checksum: $$checksumExisting"; \
+			echo "INFO  : local            $$file has checksum: $$checksumExisting"; \
 			if [ "$$checksumEntry" = "$$checksumExisting" ]; then \
-				echo "INFO  : Analyse checksum for $$file (CHECKSUM-MATCH)"; \
+				echo "INFO  : analyse checksum $$file (CHECKSUM-MATCH)"; \
 				continue; \
 			else \
-				echo "NOTICE: Analyse checksum for $$file (CHECKSUM-MISMATCH)"; \
+				echo "NOTICE: analyse checksum $$file (CHECKSUM-MISMATCH)"; \
 				download=1; \
 			fi; \
 		else  \
-			echo "NOTICE: Download source: $$urlEntry (MISSING)"; \
+			echo "NOTICE: download source: $$urlEntry (MISSING)"; \
 			download=1; \
 		fi; \
 		if [ $$download -eq 1 ]; then \
-			echo "INFO  : Download source: $$urlEntry to file $$file"; \
+			echo "INFO  : download source: $$urlEntry to file $$file"; \
 			curl -s -o $$file $$urlEntry; \
 			r=$$?; \
 			if [ $$r -eq 0 ]; then \
-				echo "INFO  : Download source: $$urlEntry (SUCCESS)"; \
+				echo "INFO  : download source: $$urlEntry (SUCCESS)"; \
+				echo "INFO  : index entry for  $$file has checksum: $$checksumEntry"; \
+				checksumExisting=$$(sha256sum $$file | awk '{ print $$1 }'); \
+				echo "INFO  : local            $$file has checksum: $$checksumExisting"; \
+				if [ "$$checksumEntry" = "$$checksumExisting" ]; then \
+					echo "INFO  : analyse checksum $$file (CHECKSUM-MATCH)"; \
+					continue; \
+				else \
+					echo "NOTICE: analyse checksum $$file (CHECKSUM-MISMATCH)"; \
+					exit 1; \
+				fi; \
 			else \
-				echo "ERROR : Download source: $$urlEntry (ERROR)"; \
+				echo "ERROR : download source: $$urlEntry (ERROR)"; \
 				exit 1; \
 			fi; \
 		fi; \
